Repository epinio/docs, pull requests merged in 2022-07, with the labels that each got.

#145 Epinio journey: single dev workflow
  docs/tutorials/single-dev-workflow.md
Labels: documentation

#153 HowTo and Reference for Routing Secrets
  docs/howtos/create_custom_appcharts.md
  docs/howtos/create_custom_service.md
  docs/howtos/custom_builder.md
  docs/howtos/custom_routes.md
  docs/howtos/install_epinio_on_k3d.md
  docs/howtos/install_epinio_on_k3s.md
  docs/howtos/install_epinio_on_minikube.md
  docs/howtos/install_epinio_on_public_cloud.md
  docs/howtos/install_epinio_on_rancher.md
  docs/howtos/install_epinio_on_rancher_desktop.md
  docs/howtos/install_epinio_on_rke.md
  docs/howtos/install_metrics_server.md
  docs/howtos/install_wordpress_application.md
  docs/howtos/port_forwarding.md
  docs/howtos/setup_routing_secrets.md
  docs/howtos/using_custom_appcharts.md
  docs/references/routing_secrets.md
Labels: bug

#154 Reference docs for Cert Manager component
  docs/references/cert-manager.md
Labels: enhancement

#155 Extended documentation of app charts
  docs/howtos/create_custom_appcharts.md
  docs/references/customization/appcharts.md
  docs/references/customization/routing_secrets.md
Labels: enhancement
