Repository epinio/docs, pull requests merged in 2023-08, with the labels that each got.

#264 Added Git Configuration docs
  docs/howtos/create_git_configuration.md
  docs/references/git_configuration.md
Labels: kind/enhancement

#265 explain usage of custom values for services in more detail
  docs/howtos/using_custom_service_values.md
Labels: kind/enhancement

#269 Regularizing the use of How-to.
  docs/explanations/advanced.md
  docs/howtos/_category_.json
  docs/howtos/customization/create_custom_appcharts.md
  docs/howtos/customization/create_custom_service.md
  docs/howtos/customization/setup_routing_secrets.md
  docs/howtos/other/port_forwarding.md
  docs/howtos/other/using_custom_appcharts.md
  docs/howtos/use-develop/debug.md
  docs/howtos/use-develop/install_wordpress_application.md
  docs/installation/install_epinio.md
  docs/installation/other_inst_scenarios/install_epinio_on_eks.md
  docs/installation/other_inst_scenarios/install_epinio_on_k3d.md
  docs/installation/other_inst_scenarios/install_epinio_on_k3s.md
  docs/installation/other_inst_scenarios/install_epinio_on_rancher.md
  docs/installation/other_inst_scenarios/install_epinio_on_rancher_desktop.md
  docs/intro.md
  docs/references/configurations.md
  docs/references/customization/appcharts.md
  docs/references/customization/catalog.md
  docs/references/git_configuration.md
Labels: area/documentation

#275 Update trace flags in references
  docs/references/commands/cli/epinio.md
  docs/references/commands/cli/epinio_client-sync.md
  docs/references/commands/cli/epinio_completion.md
  docs/references/commands/cli/epinio_info.md
  docs/references/commands/cli/epinio_login.md
  docs/references/commands/cli/epinio_logout.md
  docs/references/commands/cli/epinio_push.md
  docs/references/commands/cli/epinio_server.md
  docs/references/commands/cli/epinio_target.md
  docs/references/commands/cli/epinio_version.md
Labels: area/documentation

#276 Move inst before tutorials
  docs/howtos/_category_.json
  docs/installation/_category_.json
  docs/references/_category_.json
  docs/tutorials/_category_.json
Labels: area/documentation, kind/enhancement

#283 Installation docs. First pass review and changes.
  docs/installation/install_epinio.md
Labels: area/documentation

#295 epinio CLI install - Refresh, typos, etc.
  docs/installation/install_epinio_cli.md
Labels: area/documentation
