Repository epinio/docs, pull requests merged in 2023-11, with the labels that each got.

#370 Coloured icons for the 'More from SUSE' menu.
  src/css/icon_dropdown.css
Labels: area/documentation

#369 Refresh language in the how to contribute doc.
  docs/howtos/contribute.md
Labels: area/documentation

#371 Refresh of the how-tos on AWS IAM and metrics server.
  docs/howtos/operations/aws_iam_integration.md
  docs/howtos/operations/install_metrics_server.md
Labels: area/documentation

#372 Fixed missing escape for dollar sign in command
  docs/references/authorization.md
  versioned_docs/version-0.9.0/references/authorization.md
  versioned_docs/version-1.0.0/references/authorization.md
  versioned_docs/version-1.1.0/references/authorization.md
  versioned_docs/version-1.10.0/references/authorization.md
  versioned_docs/version-1.2.0/references/authorization.md
  versioned_docs/version-1.3.0/references/authorization.md
  versioned_docs/version-1.4.0/references/authorization.md
  versioned_docs/version-1.5.0/references/authorization.md
  versioned_docs/version-1.5.1/references/authorization.md
  versioned_docs/version-1.5.2/references/authorization.md
  versioned_docs/version-1.6.0/references/authorization.md
  versioned_docs/version-1.6.1/references/authorization.md
  versioned_docs/version-1.6.2/references/authorization.md
  versioned_docs/version-1.7.0/references/authorization.md
  versioned_docs/version-1.7.1/references/authorization.md
  versioned_docs/version-1.8.0/references/authorization.md
  versioned_docs/version-1.8.1/references/authorization.md
  versioned_docs/version-1.9.0/references/authorization.md
Labels: kind/bug

#360 Added new Authorization Roles
  docs/howtos/customization/create_custom_role.md
  docs/references/authentication_oidc.md
  docs/references/authorization.md
Labels: area/documentation

#373 All the shorter customization how-to documents.
  docs/howtos/customization/create_custom_appcharts.md
  docs/howtos/customization/create_custom_role.md
  docs/howtos/customization/create_custom_service.md
  docs/howtos/customization/create_git_configuration.md
  docs/howtos/customization/custom_builder.md
  docs/howtos/customization/custom_routes.md
  docs/howtos/customization/export_to_oci_registries.md
  docs/howtos/customization/provision_external_ip_for_local_kubernetes.md
  docs/howtos/customization/setup_export_registry.md
  docs/howtos/customization/setup_external_registry.md
  docs/howtos/customization/setup_external_s3.md
  docs/howtos/customization/setup_routing_secrets.md
  docs/howtos/customization/using_custom_service_values.md
  src/css/custom.css
Labels: area/documentation

#374 Unsaved changes to frontmatter, now in this commit.
  docs/howtos/customization/create_custom_role.md
  docs/howtos/customization/custom_routes.md
  docs/howtos/customization/export_to_oci_registries.md
  docs/howtos/customization/provision_external_ip_for_local_kubernetes.md
  docs/howtos/customization/setup_export_registry.md
  docs/howtos/customization/setup_external_registry.md
  docs/howtos/customization/setup_external_s3.md
Labels: area/documentation

#377 Refresh of the howtos/use-develop.
  docs/howtos/use-develop/debug.md
  docs/howtos/use-develop/export-and-transfer.md
  docs/howtos/use-develop/install_wordpress_application.md
  docs/howtos/use-develop/namespaces.md
Labels: area/documentation

#380 Added missing note about server restart after creating new roles, and rephrased to active voice
  docs/howtos/customization/create_custom_role.md
Labels: kind/bug

#381 Refresh of all the 'Other' how-tos.
  docs/howtos/other/certificate_issuers.md
  docs/howtos/other/gitjob_push.md
  docs/howtos/other/minio.md
  docs/howtos/other/port_forwarding.md
  docs/howtos/other/separate_workload_ingress.md
  docs/howtos/other/using_custom_appcharts.md
Labels: area/documentation

#382 Document the new `env` key for staging script specs.
  docs/references/customization/staging-scripts.md
Labels: kind/enhancement

#385 how to recover from a CRD deletion mishap
  docs/howtos/use-develop/app_recover.md
Labels: area/documentation

#384 Document epinio operation without cert-manager.
  docs/references/cert-manager.md
Labels: area/documentation, kind/enhancement

#388 Refresh reference system requirements.
  docs/references/system_requirements/global.md
  docs/references/system_requirements/windows.md
Labels: area/documentation

#389 Two small fixes in recent work.
  docs/howtos/use-develop/app_recover.md
  docs/references/cert-manager.md
Labels: kind/bug, area/documentation

#390 Updated info cli docs
  docs/references/commands/cli/epinio_info.md
Labels: area/documentation
